---
ansible_user: admin
ansible_password: admin
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
# AVD paths
execute_tasks: false
root_dir: "{{ playbook_dir | replace('/playbooks', '') }}"
documentation_dir_name: "artifacts/documentation"
output_dir_name: "artifacts/intended"
post_running_config_backup_dir_name: "artifacts/config_backup"
eos_validate_state_name: "artifacts/reports"
test_catalogs_dir_name: "test_catalogs"
# AVD configurations
fabric_dir_name: "{{ fabric_name }}"
avd_data_conversion_mode: error
avd_data_validation_mode: error
avd_ignore_requirements: true
use_anta: true
save_catalog: true
