---
- name: Build EOS config
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false

  tasks:
    - name: run python installs
      ansible.builtin.command: pip3 install -r ../avd-install.txt
      delegate_to: localhost

    - name: Generate intended variables
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate device intended config and documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
