---
- name: Build EOS config
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false

  vars:
    fabric_dir_name: "{{ fabric_name }}"
    execute_tasks: false
    documentation_dir_name: "artifacts/documentation"
    output_dir_name: "artifacts/intended"

  tasks:

    - name: Generate intended variables
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi
