---
- name: Build EOS config
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false

  tasks:
    - name: Generate intended variables
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi
