---
- name: Validate deployed config
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false

  vars:
    fabric_dir_name: "{{ fabric_name }}"
    execute_tasks: false
    root_dir: "artifacts"
    save_catalog: true

  tasks:
    - name: Validate EOS state
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        use_anta: false
        eos_validate_state_name: reports

    # - name: Validate EOS state with ANTA
    #   delegate_to: localhost
    #   ansible.builtin.import_role:
    #     name: arista.avd.eos_validate_state
    #   vars:
    #     use_anta: true
    #     eos_validate_state_name: atna_reports
