---
- name: Validate deployed config
  hosts: ATD_FABRIC
  connection: local
  gather_facts: false

  tasks:
    - name: Validate EOS state
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state

    - name: Validate EOS state with ANTA
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      delegate_to: localhost
      vars:
        use_anta: true
        save_catalog: true
