---
name: Deploy updates

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-linters:
    timeout-minutes: 15
    runs-on: avd-ci
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run yamllint
        uses: karancode/yamllint-github-action@v2.1.1

      - name: run ansible-lint
        uses: ansible/ansible-lint@v6.22.0

      - name: run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v13.0.0

  dev-build-deploy-test:
    needs: run-linters
    env:
      ANTA_PASSWORD: ${{ secrets.ANTA_PASSWORD }}
      SUDO_PASS: ${{ secrets.SUDO_PASS }}

    timeout-minutes: 15
    runs-on: avd-ci
    steps:
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install requirements
        run: ./setup.sh

      - name: build with AVD
        run: ansible-playbook playbooks/build.yml

      - name: create topology with containerlab
        run: echo $SUDO_PASS | sudo -S clab deploy -t lab.yml --reconfigure

      - name: deploy configuration to nodes
        run: |
          ansible-playbook playbooks/deploy-net.yml
          sleep 10

      - name: run ANTA tests
        run: |
          anta \
              --username admin \
              --password $ANTA_PASSWORD \
              -i anta/anta-inv.yml \
              --log-file artifacts/anta.log \
              nrfu --catalog anta/anta-test.yml text

      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: avd-artifacts
          path: artifacts/**
          retention-days: 90

      - name: destroy lab
        if: always()
        run: echo $SUDO_PASS | sudo -S clab destroy -t lab.yml -c

      - name: cleanup self hosted runner
        uses: TooMuch4U/actions-clean@v2.1
