name: Deploy updates

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    env:
      ANTA_PASSWORD: ${{ secrets.ANTA_PASSWORD }}
      ANTA_USERNAME: ${{ vars.USERNAME }}
      ANTA_INVENTORY: ${{ vars.INVENTORY }}

    timeout-minutes: 15
    runs-on: avd-ci
    steps:
      - name: hi
        run: echo "Hello World!"

      - name: checkout
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v3

      - name: install requirements
        run: |
          pip3 install "ansible-core<2.15.0"
          ansible-galaxy collection install arista.avd
          export ARISTA_AVD_DIR=$(ansible-galaxy collection list arista.avd --format yaml | head -1 | cut -d: -f1)
          pip3 install -r ${ARISTA_AVD_DIR}/arista/avd/requirements.txt

      - name: deploy toplogy with clab
        run: clab deploy -t lab.yml

      - name: build
        run: ansible-playbook build.yml

      - name: deploy to nodes
        run: ansible-playbook deploy-net.yml

      - name: install ANTA and run tests
        run: |
          pip3 install anta
          anta nrfu --catalog anta-test.yml table

      - name: destroy lab
        if: always()
        run: clab destroy -t lab.yml --clean-up
