---
name: Network CI

on:
  # pull_request:
  #   branches:
  #     - main
  push:
    branches:
      - main

jobs:
  run-linters:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4

      - name: run pre-commit
        uses: pre-commit/action@v3.0.0

  dev-build-deploy-test:
    needs: run-linters
    env:
      ANTA_PASSWORD: ${{ secrets.ANTA_PASSWORD }}
      SUDO_PASS: ${{ secrets.SUDO_PASS }}
      CEOS_VERSION: 4.30.2F

    timeout-minutes: 15
    runs-on: avd-ci
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install requirements
        run: pip install invoke && invoke setup-base

      - name: create topology with containerlab
        run: echo $SUDO_PASS | sudo -S containerlab deploy -t lab.yml --reconfigure

      - name: build with AVD
        run: ansible-playbook playbooks/build.yml

      - name: deploy configuration to nodes
        run: |
          ansible-playbook playbooks/deploy-net.yml
          sleep 10

      - name: run ANTA cli tests
        run: |
          anta \
              --username admin \
              --password $ANTA_PASSWORD \
              --inventory anta/anta-inv.yml \
              --log-file artifacts/anta.log \
              nrfu --catalog anta/anta-test.yml text

      - name: validate configuration on nodes
        run: ansible-playbook playbooks/validate-net.yml

      - name: validate configuration on nodes w/anta
        run: ansible-playbook playbooks/validate-net-anta.yml

      - name: destroy lab
        if: always()
        run: echo $SUDO_PASS | sudo -S containerlab destroy -t lab.yml -c

      - name: cleanup self hosted runner
        if: always()
        uses: TooMuch4U/actions-clean@v2.1
